spring:
  config:
    activate:
      on-profile: local

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000
      password: qwer1234

  datasource:
    url: jdbc:mysql://localhost:3306/delivery
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        format-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 604dab1be12d78d6c4a9d535131f3f55
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/{registrationId}
            scope:
              - profile_nickname
              - account_email

          naver:
            client-id: 2QiHBn_BGIbphFrA_oUk
            client-secret: 6j0V_sou4z
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/{registrationId}
            scope:
              - name
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.hibernate.type.descriptor.sql: TRACE


jwt:
  secret-key: yourSuperSecretKey1234567890yourSuperSecretKey1234567890
  access-token-expiration: 360000000000
  refresh-token-expiration: 604800000
  header: Authorization
  prefix: Bearer

payment:
  toss:
    secret_api_key: test_sk_yL0qZ4G1VOmv5N7LMlo8oWb2MQYg
    success_url: http://localhost:8080/api/v1/points/charge/success
    fail_url: http://localhost:8080/api/v1/points/charge/fail
    origin_url: https://api.tosspayments.com/v1/payments/